### PR TITLE
Clone of Mint Sign-up Page 

### PR DESCRIPTION
**Pull request by ElijahTobs**
**Fixed all changes as requested by the TSE**

- vertically aligned the buttons
- added a new screenshot of the page
- fixed the part that wasn't showing in the live demo and firefox

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### This an awesome job Team 👏👏👏

**I particularly love the fact that you made use of semantic HTML tags.👌👍👍**

However, there remain a few minor changes that need to be made before moving forward.

- [x] Add a live version link to your readme, consider using the [githack](https://raw.githack.com/) tool for this purpose.

- [x] Kindly remove all comments in your code files. It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

- [x] Also there exists a single error in your HTML validation, kindly use this [tool](https://validator.w3.org/nu) to check for validation in your HTML file and fix it.

- [x] Please add a space between your form label elements and your input elements.

**This is yours👇[Screenshot]**
ice_screenshot_20200330-125930

**This is what it's supposed to be👇[Screenshot]**
ice_screenshot_20200330-130040

- [x] Also please remove this item on the bottom right corner of your webpage as it doesn't exist on the original.[Screenshot]👇
ice_screenshot_20200330-130142

- [x] The `Learn more` text in the form is a link element, kindly fix that. 
**This is yours👇[Screenshot]**
ice_screenshot_20200330-130227

**This is the way it's supposed to be👇[Screenshot]**
ice_screenshot_20200330-130234

**Apart from these issues your project looks top-notch.**👌

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️  🚥 

Hi **TEAM**, you have done a great job working on the comments pointed out by the previous TSE 👍 However, before we can proceed, we need to address the following issues: 😄 
* Below the intuit, let us replace the images with the images and text. Currently, we have 1 image for all three items. Kindly check the image below
logo-txt
* Kindly edit the PR Pull Request so it describes what the project is about [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
* Let us apply the DRY rule to the CSS file, so we make it more cleaner
* Let us improve our README file. Add screenshots  and email to the author section
* Currently, the LIVE link is not working. Kindly fix it
* In our next projects, we should make our commits in the present tense. Example, add instead of added

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Comment by uryelah** [comment]
Hello **Elijah Ayandokun** & **Godson Tendongze Zeingkeang**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all great job with the form styling and fixing most of the last required changes🌟**

There's still some work to be done before you can move on so read the bellow checklist carefully and implement it the best you can. Keep up the good work 💪

---------    

## Required Changes 🏗 
 
- [x] It seems that something broke while making the fixes from the last review. Make sure the logo and the images bellow it are showing up. They are currently not working, I checked both on firefox and chrome.
Screenshot_2020-03-30 Sign Up

- [x] On firefox the button text is not vertically centered, make sure it's working on this browser too.
Screenshot_2020-03-30 Sign Up(1)

- [x] The last TSE asked you to fix your Pull Request message, try to follow the model in the gif bellow with bullet points:
69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2


----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Dandush03** [comment]
### :heavy_check_mark: Project Approve :boom:  :checkered_flag:
# Hey @ElijahTobs @tGodson  :hand: 
### Great Job so Far :grey_exclamation: :grey_exclamation: :muscle: :smiley: 

### Following Previous Reviews and Seeing you Have Made Required Changes. 
### The project Looks Great.:grey_exclamation::wink:

## [_Optional_]
* [ ] try adding a title to your PR so it would look more professional :wink:

### Good Luck in your Next Assigment
### Happy coding:computer: 
#### Daniel Laloush

**Pull request merged**
